### ISSUE TITLE
ganglia-web-3.7.1 installation problems

### ISSUE THREAD

**Issue by steve-YEG** [ganglia/ganglia-web#276]
I am trying to install ganglia-web-3.7.1 on a CentOS 6.7 cluster head node and I find that the installation web page: https://github.com/ganglia/ganglia-web/wiki#Installation confusing at best.  

In the first section--Installation--It starts by saying: "Latest release of Ganglia Web 2" but isn't the latest release maybe Web 3?  The example for doing the untar and renaming in the second sentence is for an even older gweb-1

In the second section--Makefile Install--it says: "Adjust the `DESTDIR` to where you copied the files".   There is no definition of DESTDIR, just GDESTDIR.  I assume that "adjust" includes defining "DESTDIR", but that is not the normal meaning. 

I followed the instructions and did the "make install >stdout" to see what it was doing.  Not what I thought that it would:
[stdout.txt](https://github.com/ganglia/ganglia-web/files/201328/stdout.txt)

I will get rid of all of those bogus paths and see if I can do the "Manual Install"

I am pretty sure that the "Manual Install" instructions also have several errors:

The first two lines set the APACHE_USER to "apache" (which is correct for Centos/RHEL, but then DEST_DIR="/var/www/ganglia2" is what is needed for Ubuntu/Debian.  Also, why does the Makefile use "DESTDIR" and the Manual Install use "DEST_DIR"--two, similar, names for the same entity?

This line:
sed -e "s|@varstatedir@|/var/lib|" conf_default.php.in > conf_default.php
should be:
sed -e "s|@vargwebstatedir@|/var/lib/ganglia|" conf_default.php.in > conf_default.php

The "Troubleshooting" section assumes possibly Ubuntu--there is no /etc/apache\*  on CentOS/RHEL.   "httpd", the default for Centos/RHEL, puts its files in /etc/httpd{conf,conf.d}/*.  In my case I do not need for this alias as I  am doing a new install and do not need multiple variants installed at the same time. 

Thank you,
       steve.

**Comment by vvuksan** [comment]
Please try with the latest version.
