### ISSUE TITLE
mistake in Ganglia Nagios Integration wiki

### ISSUE THREAD

**Issue by JavyZheng** [ganglia/ganglia-web#282]
As in my integration, there is a mistake in the [Ganglia Nagios Integration Wiki](https://github.com/ganglia/ganglia-web/wiki/Nagios-Integration). As shown below:

```
define command {
  command_name  check_ganglia_heartbeat
  command_line  /bin/sh /var/www/html/ganglia/nagios/check_heartbeat.sh host=$HOSTADDRESS$ threshold=$ARG1$
}
```

`host=$HOSTADDRESS$` should be `host=$HOSTNAME$`.

***
say we have a server with `ip=192.168.0.7` and `hostname=server007`

if we pass ip to check_heartbeat.sh
```
./check_heartbeat.sh host=192.168.0.7 threshold=20
```
I will get following error message:
```
UNKNOWN 192.168.0.7 - Hostname info not available. Likely invalid hostname
```

if we pass hostname to check_heartbeat.sh
```
./check_heartbeat.sh host=server007 threshold=20
```
I will get the right message like:
```
OK Last beacon received 0 days, 0:00:14
```

**Comment by vvuksan** [comment]
Thanks for the correction. Documentation has been updated.
