### ISSUE TITLE
(Query) Can anyone help what is V param in ganglia web url 

### ISSUE THREAD

**Issue by ravindhar** [ganglia/ganglia-web#288]
http://xx.xx.xx.xx/ganglia/graph.php?c=my%20cluster&h=compute1&r=custom&z=large&jr=&js=&st=1467780024&cs=06%2F01%2F2016%2000%3A00&ce=06%2F30%2F2016%2000%3A00&v=0.30&m=pphjditimis2157.vcpu_util&vl=%25&ti=pphjditimis2157%3A%20VM%20CPU%20Utilization&json=1

**Comment by vvuksan** [comment]
It is the current value of the metric. It will show up in the legend as (now 0.30)

**Comment by ravindhar** [comment]
How will I get this value and If I  not pass this value in the above url is there any change in response
