### ISSUE TITLE
gweb master :: php error [] operator not supported

### ISSUE THREAD

**Issue by adriansev** [ganglia/ganglia-web#303]
Hi! with the latest gweb  (and php 7.1.0) i get this :

[Sun Aug 14 21:09:33 2016] [error] [client xxxxx] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/html/ganglia/cluster_view.php:33\nStack trace:\n#0 /var/www/html/ganglia/cluster_view.php(781): get_picker_metrics(Array, Array, '/var/www/html/g...', 'rrdtool')\n#1 {main}\n  thrown in /var/www/html/ganglia/cluster_view.php on line 33, referer: http://my_fqdn/ganglia/?r=year&cs=&ce=&m=load_one&s=by+name&c=ISS-ALICE&tab=m&vn=&hide-hf=false

i imagine that this is because of the php version, but can this be solved for any php version?
Thank you!
Adrian

**Comment by adriansev** [comment]
so, this was solved by replacing    
context_metrics = "";  
with  
$context_metrics = array();  
can this be implemented? thank you!

**Comment by vvuksan** [comment]
Can you submit this as a pull request?

**Comment by adriansev** [comment]
sure, done. thanks!
