### ISSUE TITLE
(Query) Host colors based on utilization value

### ISSUE THREAD

**Issue by ravindhar** [ganglia/ganglia-web#310]
Utilization is: (1 min load) / (number of CPUs) * 100%.
Why ganglia-web used above formula to give the colors why not 1 min load
can any one elaborate this

**Comment by vvuksan** [comment]
Load and how busy a system is with multiple CPUs is correlated e.g. a 4 CPU system with load 4 is a lot busier than a 16 CPU system with load 4.

**Comment by ravindhar** [comment]
Thank you @vvuksan
