### ISSUE TITLE
No option to create View under Views Tab

### ISSUE THREAD

**Issue by MayankSainiTk20** [ganglia/ganglia-web#311]
Hi,

I have installed Ganglia Web Frontend version 3.7.1 on a machine and there is no option to create a view there. Please look at the attached screenshot and let me know if I need to do some confrontational changes.

![capture](https://cloud.githubusercontent.com/assets/8155434/18879028/82de5ed8-84f0-11e6-8c5f-4c906a4c3213.JPG)
Thanks,
Mayank

**Comment by vvuksan** [comment]
Hi Mayank,

For security reasons it's disabled by default. Please read

https://github.com/ganglia/ganglia-web/wiki/Authorization-System

on details how to enable it.
