### ISSUE TITLE
Time specific graphs under Aggregated graphs tab

### ISSUE THREAD

**Issue by akellaumesh** [ganglia/ganglia-web#312]
Hi, 

I think it could be good if you can include "TIME" as well under the aggregated graphs tab. It would be interesting to view the performance of the server from this specific time to a particular specific time.

Only Hostname & Metric compatibility is included under that tab.

**Comment by akellaumesh** [comment]
Update on issue:

The main idea was to implement 
A SPECIFIC TIME tag under the Aggregated graphs Tab 
specific time means, I would like to view, the graph from one start time to an end time.  That means, I should be able to select a start time and an end time including the date.
As you can see the idea I was telling is under VIEWS tab and EVENTS tab

**Comment by afbjorklund** [comment]
There is a problem with the "aggregrate graphs" tab, and that is that is just a simple form and not a templated component like the other tabs are. This makes it harder to add the standard elements...
Furthermore there is no page for showing a graph for a single period, just for all periods. But adding a form element to input time, and displaying as an image - that is fairly straightforward. Will add, shortly.
