### ISSUE TITLE
how to visualize most active users

### ISSUE THREAD

**Issue by kirk86** [ganglia/ganglia-web#339]
Hi and thanks for making ganglia.
I was wondering if its possible to get a plot of the most active users, i.e. 1) users who run the most jobs and 2) users whose work has the highest load on the server.

**Comment by vvuksan** [comment]
Only way to do this is you have to use either gmetric or gmond python module to emit those metrics to Ganglia. It is not something that Ganglia web does on it's own.

**Comment by afbjorklund** [comment]
@kirk86 : ganglia is not very good at visualizing _lists_ of very different things, like user names.
You can easily view a graph of the **number** of jobs or the current load average, as time series.

But if you want to report the **names** of the users with the most jobs, or using the most CPU -
then you are better off using something more similar to a distributed "top" in terms of database ?

**Comment by kirk86** [comment]
Thanks folks, @afbjorklund & @vvuksan!
